### ISSUE TITLE
Replacement of internal Mailform does not work

### ISSUE THREAD

**Issue by TN03** [cmb69/advancedform_xh#39]
See: https://cmsimpleforum.com/viewtopic.php?f=16&t=14022&p=67572#p67567

**Comment by cmb69** [comment]
Aargh! The detested sloppyness of CMSimple's URLs. It works, if `?mailform` is requested in the first place. Anyhow, what do you think about the following simple fix:
````diff
 advfrm.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/advfrm.php b/advfrm.php
index 7d26a18..2fa5948 100644
--- a/advfrm.php
+++ b/advfrm.php
@@ -1044,7 +1044,7 @@ function Advancedform_formView($id)
     Advancedform_initJQuery();
     $o = '';
     $o .= '<div class="advfrm-mailform">' . PHP_EOL
-        . '<form name="' . $id . '" action="' . $sn . '?' . $su . '" method="post"'
+        . '<form name="' . $id . '" action="' . $sn . '?' . ($su ? $su : '&mailform') . '" method="post"'
         . ' enctype="multipart/form-data" accept-charset="UTF-8">' . PHP_EOL
         . tag('input type="hidden" name="advfrm" value="'.$id.'"') . PHP_EOL
         . '<div class="required">'
````

**Comment by TN03** [comment]
> It works, if ?mailform is requested in the first place.

But that should result in an Error 404, because there is no page called "Mailform".

> Anyhow, what do you think about the following simple fix:

Should work :)

**Comment by cmb69** [comment]
> But that should result in an Error 404, because there is no page called "Mailform".

Perhaps it should, but it doesn't!

**Comment by TN03** [comment]
Please have a look here: https://cmsimpleforum.com/viewtopic.php?f=16&p=67580&sid=7230b9c007ecebfac16e488224370244#p67580

**Comment by cmb69** [comment]
But see <https://cmsimpleforum.com/viewtopic.php?f=16&t=14022&p=69694#p69694>.
