### ISSUE TITLE
⚠️ Confirmation mail abuse

### ISSUE THREAD

**Issue by cmb69** [cmb69/advancedform_xh#53]
See <https://cmsimple.org/forum/viewtopic.php?t=886&p=2782#p2782>.

Maybe a documentation issue (“always define a thanks-page; otherwise …”)? 

PS: but maybe we should drop confirmation mails altogether?

**Comment by frase-git** [comment]
> Maybe a documentation issue (“always define a thanks-page; otherwise …”)?

+1

> PS: but maybe we should drop confirmation mails altogether?

Please do not remove, this is occasionally needed.

**Comment by cmb69** [comment]
> Please do not remove, this is occasionally needed.

It's dangerous, though, since anybody can send mail on your behalf – any mail, not only “harmless” spam, but even mail with indictable contents.
