### ISSUE TITLE
get_magic_quotes_runtime() - Error message

### ISSUE THREAD

**Issue by frase-git** [cmb69/advancedform_xh#57]
When calling the plugin overview page (and only there) an error message appears under PHP 7.4.x:

> DEPRECATED: Function get_magic_quotes_runtime() is deprecated
> ... \plugins\advancedform\admin.php:112

Do you have a quickfix? The clientele is confused.

**Comment by cmb69** [comment]
When using PHP 5.4.0 or later, I think you can just removed these lines:
https://github.com/cmb69/advancedform_xh/blob/a419d411bb1e8137f3a75e7d5710b40b175d1796/admin.php#L112-L113

**Comment by frase-git** [comment]
Works!
Thank you!
Now I do not have to explain so much ;-)

**Comment by cmb69** [comment]
Fixed as 4f69bba269ceebb35b70361baa5f278a35ca33c1.
