### ISSUE TITLE
Font size "xx-small" is too small

### ISSUE THREAD

**Issue by frase-git** [cmb69/advancedform_xh#61]
v2.0
Advancedform - Mail Forms:
The font size for `#advfrm-form-list td.script` is set to` xx-small`. This is really small and not readable in some templates. Maybe `inherit` would be better at this point.
(This has bothered me already in earlier versions).

Proposal:
... \advancedform\css\stylesheet.css
Line 92
`font-size: inherit;`

**Comment by cmb69** [comment]
Well, actually there shouldn't be the need to read that text at all; it's just meant for copying it to the clipboard, and pasting it into the desired page. It is, however, not easily possible to copy arbitrary text into the clipboard with client side JS.

I've choosen the very small text size to avoid layout issues on small screens/templates, especially  if the form names are long. Maybe it would be option to omit the `font-size` declaration, and to limit the size of the input element (`<input size="1" …>`). What do you think about this?

Also, in the long run, these inputs should go in favor of some plugin-call-editor.

**Comment by frase-git** [comment]
Layout problems only exist because it is a table. That could be changed.
On the other hand, one could copy automatically into the clipboard - with `execCommand('copy')`.
Example:
`<input title="to clipboard" type="button" value="{{advancedform('MyForm')}}" onClick="this.form.code.select(); this.form.code.focus(); document.execCommand('copy')">`
Then the input field can also have `size="1"` - however, I prefer to see what I'm copying beforehand.

**Comment by cmb69** [comment]
`execCommand('copy')` may work, or not. Or it may trigger some confirmation, or what not. Other APIs appear to have similar issues. I really don't want to look into this.

I also don't want to spend much time on this in general, so I'm just going to remove the explicit font-size declaration (users who desire so can then still customize).
