### ISSUE TITLE
Enable focus also on radio buttons and checkboxes

### ISSUE THREAD

**Issue by frase-git** [cmb69/advancedform_xh#81]
https://cmsimpleforum.com/viewtopic.php?p=80167#p80167

Solution:
Delete `'checkbox'` and `'radio'` from [this line](https://github.com/cmb69/advancedform_xh/blob/26b2ada2e4e548232d84f861a873eb99e139b3ba/classes/MailFormController.php#L159)

**Comment by cmb69** [comment]
Indeed, this is a bug, but my suggested solution would mark the main label of checkboes/radiobuttons as `<label>` what wouldn't make sense.
