### ISSUE TITLE
incompatible return type of ::jsonSerialize()

### ISSUE THREAD

**Issue by frase-git** [cmb69/advancedform_xh#88]
XH 1.7.5
PHP 8.1.1 (xampp win)
Advancedform 2.3

Pluins – Advancedform – Mail Forms
Debug mode wrote:

> DEPRECATED: Return type of Advancedform\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ... \plugins\advancedform\classes\Form.php:182
> DEPRECATED: Return type of Advancedform\Field::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ... \plugins\advancedform\classes\Field.php:125

The messages are also displayed when you go to a page with a form.

**Comment by cmb69** [comment]
Ah, right. Thanks for reporting!
